### ISSUE TITLE
SPIKE: BUG: Connection to DB reset by peer after PROD deploy

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1251]
## Description
We are seeing connections reset because we are very likely improperly shutting down our ECS tasks. We fall into the trap specifically called out in an [AWS Blog](https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/) regarding, "One PID to rule them all". That blog expertly paints a picture that matches our setup and the problem we face. 

To fix this issue we need to implement the suggestions listed in the blog or any other approaches that will fix the core issue: non-graceful shutdowns. There are many possible options, so this spike should investigate options and create a follow-on ticket for implementation based on what is found during this spike.

Note: Significant time was spent to make it to this point in our understanding, so this spike is pointed higher than normal.

## Steps to Reproduce
Any deploy action with active requests should replicate this issue.

## Workaround
A potential workaround (short-term) may be to change the deregistration delay of the ECS task to 25 seconds so most requests would finish processing. If the `SIGKILL` signal comes 30 seconds after the `SIGTERM` and the `SIGTERM` signal is sent at the same time as a deregistration delay, we can deregister new requests 25 seconds into the `SIGTERM`, so all new requests are routed to the new tasks. This is only possible if our tasks take less than 25 seconds to start, and we would have to monitor that moving forward.

## Impact/Urgency
High impact/urgency. A variety of scenarios can result in this unplanned termination such as data not making it to the database, delivering email/sms not making it all the way through, persistent notifications not getting set, etc. This has drastic consequences. 

## Expected Behavior
We expect that tasks in work will not just stop running. The purpose of this bug spike is to identify a path to move forward. New ticket(s) must be created to implement a fix for this bug. 

## Acceptance Criteria

- [x] Root cause is known
- [ ] Additional ticket(s) to resolve the issue have been created

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
![image (10).png](https://images.zenhubusercontent.com/630696b479f5cca51e546872/fadcccc1-e64f-4f23-8562-cc24be210199)

## Timebox
The remaining work (investigation and ticket creation) should be limited to a day or two.

**Comment by k-macmillan** [comment]
These connection resets happened yesterday around noon again, this time with v1.6.0 in master. I am inclined to believe this was not the root cause of the deployment issue.

**Comment by cris-oddball** [comment]
FYI - the connection reset by peer appears to be related to deployments, where the celery workers are spun up and down. we can probably remove the high priority label. Most likely related to failing to shut down properly.

**Comment by k-macmillan** [comment]
Been tracking this down. Really dug into how our system starts up, how the workers execute and what `SIGTERM` would do in our system. Was able to replicate the environment with a local substitute that sufficiently demonstrates what happens when a `SIGTERM` is sent (using `kill -15 PID`)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/61002ccd-2ecf-46aa-9b8f-80388210e891)

From the image we can see that `ddtrace-run` passes along the `SIGTERM`. However, what can't be seen from the image is that the termination is _instant_. So I have confirmed that our gunicorn workers are getting the `SIGTERM` signal, we just need to handle it better. 

This last image shows that -15 is the `SIGTERM` (-9 is `SIGKILL`).
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/24ddd120-05dd-4352-8fb6-48cd94956472)

**Comment by k-macmillan** [comment]
Worker deployed (forced redeploy) with exec at 19:45:35:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/ab8904cc-497c-4274-bd3f-66396bd0e790)
Graceful shutdown signal received at 19:47:29:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/be54bea4-bd91-4543-8668-a778cbd7ec06)

Actual shutdown method getting called:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/729c8e42-eddf-4166-af57-aed520f428cb)

So calling the celery worker with exec passes the `SIGTERM` to it. Also, seems our concurrency setting is the number of workers. I was under the impression concurrency was threads, but it seems it is [processes](https://docs.celeryq.dev/en/stable/reference/cli.html?highlight=concurrency#cmdoption-celery-worker-c).
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/3d3b6f0d-781a-403b-b919-ac7e11ba124a)

So each concurrency value is another process, not a thread to do work. That's a big deal. Essentially means we can scale that instead of calling more worker commands. Tested, and it is working as expected (tested by running the regression suite):
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/15e4e404-e1ed-4cb5-bc35-71c650758dee)

Would need actual stress testing to identify what values the workers should be set to. Also, didn't test multiple worker pools because that's outside the scope of what I was doing. The only reason I touched them at all is because as I was waiting for deploys I read up on it and it was an easy change for the next test, so I changed it.

**Comment by k-macmillan** [comment]
I investigated the connections being "reset by peer" and it does not appear to be the root of the references not being saved during deploys. The flask-sqlalchemy [documentation](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/api/#flask_sqlalchemy.SQLAlchemy.session) states that our session lasts so long as the app has context. So I'm inclined to believe that the errors are thrown because when our application exits it terminates the connection but RDS doesn't appreciate the way it does it.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/18d3c6d3-07e6-4aa2-87ad-c0245bec8ccf)
