### ISSUE TITLE
Comp and Pen - Move Celery Task Feature Flag Deeper Into the Process

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1747]
## User Story - Business Need
We want to be able to test more of our pipeline without actually sending notifications. This issue involves moving the feature flag a little deeper into the process, so we can better understand the impact of some of our code operated at scale come May.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** to see that our process is making it to pre-BIP code
**So that** we can understand the impact of X requests/second

### Additional Info and Resources

- The feature flag is: `COMP_AND_PEN_MESSAGES_ENABLED`
- The method this is used in is: `send_scheduled_comp_and_pen_sms`

New location of the flag should be in this `try` block. If a different location is desired please reach out:
<img width="603" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e1bfbfab221cd615e2205c6801e7113f1b9468b/image.png" alt="image.png" />

## Engineering Checklist
This assumes ticket #1750 is complete.

- [x] Update unit tests
- [x] Update feature flag location

## Acceptance Criteria

- [x] ~~Prod `COMP_AND_PEN_MESSAGES_ENABLED` flag value does not change~~ flag set to False in Perf at QA's request
- [x] Feature flag is in a place that prevents notifications from being sent

## QA Considerations
- [x] involve QA with testing

## Potential Dependencies
Be mindful of what is available (service, template, sms sender id). If those do not exist it will error if the feature flag allows the code to pass.

**NOTE:** sms sender may be mocked depending on code change related to no longer using the default sms sender

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1747?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by cris-oddball** [comment]
Sent back to TODO because this work is blocked by #1750, which needs to be worked first based on AC.

**Comment by cris-oddball** [comment]
This was tested prior to the merge in Perf. 

Not retesting after merge since there are too many other tickets that need to use Perf for testing. The testing we did satisfied the requirements.

Perf feature flag is disabled (this will be re-enabled when 1752 is merged). That means that a notification will be created but then not sent to the queue. is_processed will still be updated to True for processed messages so that celery doesn't continue polling the DB for the same items.

Logs of note:
>[2024-05-06 20:26:00,297: INFO/ForkPoolWorker-4] sending - item from dynamodb - vaprofile_id: 210935 | participant_id: 13352885 | payment_id: 1005

> [2024-05-06 20:26:00,297: INFO/ForkPoolWorker-4] Not sent to queue (feature flag disabled) - item from dynamodb - vaprofile_id: 210935 | participant_id: 13352885 | payment_id: 1005
[2024-05-06 20:26:00,298: INFO/ForkPoolWorker-4] updated_item from dynamodb ("is_processed" should be "True"): {'sourceTs': '2024-05-01T00:00:00+00:00', 'payment_id': Decimal('1005'), 'participant_id': Decimal('13352885'), 'is_update_allowed': Decimal('1'), 'is_processed': True, 'vaprofile_id': Decimal('210935'), 'paymentAmount': Decimal('1001.23'), 'expires_at': Decimal('1717718400')}

screenshot showing the 'not sent to queue' log
<img width="1664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1bc5f33b1779627853e64232de6d553c4e1c834/BIP-Perf-feature-flag-disabled.jpg" alt="BIP-Perf-feature-flag-disabled.jpg" />

screenshot showing the dynamoDB table with updated `is_processed` field:

<img width="1451" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGE2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd85446a408c91a1c6173a5d943713792d19f6e3/BIP-Perf-is_processed-True.jpg" alt="BIP-Perf-is_processed-True.jpg" />
