### ISSUE TITLE
Comp and Pen: Add COMP_AND_PEN_SMS_SENDER_ID to task definitions

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1749]
## User Story - Business Need
Currently the configurations we're storing in task definitions for the comp and pen SMS notification use case include: the Notification Send Feature Flag, Service ID, Template ID, and Dynamodb Table Name. Because sms sender id is not a configuration point, the code will use the service default sms sender. We want to add sms sender ID so we are explicit about what sender is being used and no default changes accidentally affect production sends.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify administrator
**I want** to define the phone number to send from
**So that** SMS are successfully sent to Veterans

## Engineering Checklist

- [x] Add the necessary infra (TF) to create an ssm variable for the sms_sender_id in each environment
- [x] Add the `COMP_AND_PEN_SMS_SENDER_ID` variable and the corresponding arn value to the celery task definitions in all environments
  - [here is the dev task definition](https://github.com/department-of-veterans-affairs/notification-api/blob/master/cd/application-deployment/dev/vaec-celery-task-definition.json#L229)

## Acceptance Criteria

- [x] `COMP_AND_PEN_SMS_SENDER_ID` exists in the celery task definitions in each environment

- [x] Specifying an sms_sender_id

> GIVEN you define a valid dynamo table name, service_id, template_id, and sms_sender_id in task definitions
> WHEN celery finds a valid payment event in dynamo during the appropriate send schedule and the send feature flag is enabled
> THEN an SMS notification is sent with the applicable sender phone number

- [x] Default sms_sender_id

> GIVEN you define a valid dynamo table name, service_id, template_id, and sms_sender_id is not populated in task definitions
> WHEN celery finds a valid payment event in dynamo during the appropriate send schedule and the send feature flag is enabled
> THEN an SMS notification is sent with the default sender phone number assigned to the service

## QA Considerations
- [x] work with developer on testing.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1749?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
I created the SSM parameters and referenced them in the API task definitions.  I still need to write some unit tests and modify the celery task code.  The ticket is still on track.  I spend a bunch of time today reviewing PRs rather than working on this ticket.

**Comment by kalbfled** [comment]
The implementation is finished, but I'm having difficulty properly mocking the unit test I created.

**Comment by kalbfled** [comment]
@mjones-oddball @k-macmillan @cris-oddball

I created a PR.  One outstanding question is what to do when the SSM parameter associated with COMP_AND_PEN_SMS_SENDER_ID has a valid UUID format, but an instance of ServiceSmsSender with that ID doesn't exist.  As currently implemented, [send_notifications_bypass_route](https://github.com/department-of-veterans-affairs/notification-api/blob/1749-comp-pen-sender-id/app/celery/scheduled_tasks.py#L379) gets called with the non-existent ID, and whatever failure logic that exists downstream gets executed.

I could change this to check in the Celery task that an associated ServiceSmsSender exists before trying to send with that ID and then use the service default if the ID is not valid.  That would cost an additional database query for every Comp & Pen message we intend to send.

**Comment by EvanParish** [comment]
Since we are setting this up for our own service I don't see the need for an extra validation step before sending to `send_notification_bypass_route`. The risk of getting an invalid ID is basically zero once we are up and running.

**Comment by cris-oddball** [comment]
This is still waiting for approvals on the PR, but we performed the testing in Perf with a cronjob set to fire today (otherwise, it's out  of that window).

**QA PASSED**

- [ ] TC01: The value of parameter is an info string. Expected: that the app defaults to the default sms sender
Logging statement showing this worked as expected:
> [2024-05-09 18:42:00,295: INFO/ForkPoolWorker-4] Using the service default ServiceSmsSender's ID.

- [ ] TC02: The value of parameter is the alternate sms_sender_id that we want the service to use for C&P notifications. Expected: that the app uses this alternate sender.
Logging statements showing this worked as expected:
<img width="1562" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzNMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--039aba9bb9a971a5d571aae8cba8fbf894c476bb/Screenshot%202024-05-09%20at%201.38.16%E2%80%AFPM.jpg" alt="Screenshot 2024-05-09 at 1.38.16 PM.jpg" />

- [ ] TC03: The value of parameter is an invalid (non-existent) sms sender id. Expected: that the app uses the default sms sender.
Logging statements showing this worked as expected:
<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aef610f80ce562a283948c0b80cf5a49f8ba58e5/Screenshot%202024-05-09%20at%201.27.07%E2%80%AFPM.jpg" alt="Screenshot 2024-05-09 at 1.27.07 PM.jpg" />

**Comment by cris-oddball** [comment]
Code was already tested in Perf and no changes were made to the PR after. Merged and sent through the pipeline to Staging.
