### ISSUE TITLE
Implementing Rate Limiting for SMS Sending

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#208]
# Value Statement:
**As** platform admin
**I want to** be able to limit the rate per number at which VANotify sends SMS to providers
**So that**our requests will not get blocked

# Acceptance Criteria

**GIVEN** a rate configured on an SMS sender ID
**WHEN** a service makes multiple requests to send notifications using that sender ID
**THEN** notifications are sent at the configured rate

**GIVEN** a rate is not configured on an SMS sender ID
**WHEN** a service makes multiple requests to send notifications using that sender ID
**THEN** we send without any artificial delays / as the notification requests come

**GIVEN** rate limiting is enabled for some SMS notifications
**WHEN** Notify processes emails or SMS notifications that are not rate limited
**THEN** their processing is not impacted

if notification is an email or using sms sender id that isn't rate limited then it just behaves as normal

# Cross Functional Checklist

Feature Toggles:
- [x] Staging - enabled
- [ ] Prod - not enabled

Monitoring:
-  [x] datadog for new retry queue

Security:
-   [x] JsonSchema

Documentation:
-   [x] Readmes - how it works and retries
-   [x] Openapi

Postman
-   [x] Update collection to specify rate limiting

New stories
- [x] [Separate queues for different SMS senders](https://github.com/department-of-veterans-affairs/notification-api/issues/563)
- [x] [Explore change in algorithm to express alg value per second](https://github.com/department-of-veterans-affairs/notification-api/issues/564)

# Assumptions:
- With the introduction of 10-DLC limits are set per campaign, not per number however since Notify doesn't have the concept of a campaign, we will rate the limit by number.

- Configure the rate on the SMS sender ID but in the future, we should refactor the whole SMS sender ID concept where we have numbers and allow services to use numbers - and then the rate-limiting would be on the numbers. This is so numbers could be shared across services.

# Additional Info/Resources:
- We can most likely reuse the solution utilized for API rate limiting
- Some articles about implementing rate limiting using redis and/or celery:
    https://www.figma.com/blog/an-alternative-approach-to-rate-limiting/
    https://gist.github.com/Vigrond/2bbea9be6413415e5479998e79a1b11a
    https://callhub.io/distributed-rate-limiting-with-redis-and-celery/
    https://alievmagomed.com/celery-throttling-setting-rate-limit-for-queues/
    https://github.com/tomasbasham/ratelimit
    https://konghq.com/blog/how-to-design-a-scalable-rate-limiting-algorithm/
    https://cloud.google.com/solutions/rate-limiting-strategies-techniques
    https://collectiveidea.com/blog/archives/2012/11/30/down-boy-how-to-easily-throttle-requests-to-an-api-using-redis
    https://dev.to/astagi/rate-limiting-using-python-and-redis-58gk
    https://ron.sh/rate-limiting-with-python-and-redis/
    https://stackoverflow.com/questions/13175050/how-to-implement-rate-limiting-using-redis
    https://flask-limiter.readthedocs.io/en/stable/
    https://medium.com/@taylorhughes/three-quick-tips-from-two-years-with-celery-c05ff9d7f9eb

# Open Questions:

- If and how will the rate limit affect other processing? Ideally whatever we build will have minimal impact on other notification processing. Should we consider different celery queues or specialized celery workers?

**Comment by miabecker** [comment]
This story will require additional technical analysis.

**Comment by vikarus-tw** [comment]
https://app.mural.co/t/thoughtworksclientprojects1205/r/1598471522381

**Comment by lingtran** [comment]
Notes for pair only to explore open question:
_perf env tests in research mode or test api key_
- [ ] send messages with SMS SENDER ID with rate limit configured (100+ messages) - want to see limit in celery task
- [ ] send a whole bunch of messages with SMS SENDER ID with rate limit configured with intermittent sending messages without rate limit set (expect the latter to go through immediately)
- [ ] send messages with two different rate limits set (to see system can handle different rate limit schemes simultaneously)

**Comment by emilywu-tw** [comment]
We added over 25k tasks to the retry queue using locust and found that even that number of tasks did not seem to overload the queue or our CPU. We tested sending emails and non-rate-limited SMSes and they were successfully sent immediately even with a ton of messages in a queue. 

However, we did find that if we attempted to send a rate-limited text with a different SMS sender with the rate limit exceeded, that task would be added to the end of the retry queue. In the future we may want to create a queue for each SMS sender, which would involve adding a new queue to our config.py file every time we add a new SMS sender and redeploying to celery. For now, we are going to put any rate-limited retries in a different queue, and we can improve this process in a future story. 

Currently, our rate limit is calculated via a window as opposed to a rolling limit. For example, if a rate limit is set to 100 messages per minute, you could have 100 messages sent in the first 1 second of the minute-long window instead of spacing it out evenly throughout the minute. We will probably want to update the redis client in notification-utils to either do something more rolling or even calculate number of messages per second. We could also limit the sends to 1 message segment per second since we probably would not want to do more than that anyway.

**Comment by lingtran** [comment]
[Rate Limit Load Tests, some results](https://app.zenhub.com/files/257953872/14f2c8aa-9a32-4901-a673-f5edd5025a13/download)

**Comment by TWs-DevenS** [comment]
This Story can be closed.  During the desk check the team was able to show the Data Dog monitoring logs as sufficient evidence for successfully meeting the acceptance criteria for all 3 scenarios.  In addition to the Integration testing performed by the team . Error Scenarios have been tested.   The documentation has been verified. Test plan to be attached.
