### ISSUE TITLE
Connect Notification-API to DB

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#28]
Add DB using Aurora

- [x] Ensure all IP addresses are used and distributed between the VPC subnets
- [x] Split VPC into two subnets [private (10.0.1.0/24) and public(10.0.0.0/24] 
- [x] Create Aurora Postgres DB into the private subnet
- [x] Ensure Notification-API can talk to Aurora Postgres
- [x] create the notification api DB 
- [x] investigate replica possibilities

**Comment by philherbert** [comment]
<img width="980" alt="Screen Shot 2020-05-15 at 12 11 58" src="https://user-images.githubusercontent.com/9078954/82072312-88603c80-96a5-11ea-8a8c-78d31473c678.png">

**Comment by philherbert** [comment]
Now that we've got the database set up, it properly connects but breaks because the tables aren't there. Yay! This will be resolved in [the migration story](https://github.com/department-of-veterans-affairs/notification-api/issues/37)*.

<img width="1017" alt="Screen Shot 2020-05-15 at 15 22 11" src="https://user-images.githubusercontent.com/9078954/82088546-f6196200-96bf-11ea-9315-bb11af6dabc8.png">

*I've also left some comments on that story about the difficulties involved in using a `postgresql` Terraform provider.

**Comment by saman-moshafi-va** [comment]
The AWS [Aurora Replication](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html) explains it all.  In short creating one read replica is sufficient for our purpose:
`To increase availability, you can use Aurora Replicas as failover targets. That is, if the primary instance fails, an Aurora Replica is promoted to the primary instance. There is a brief interruption during which read and write requests made to the primary instance fail with an exception, and the Aurora Replicas are rebooted. `
> 

>

**Comment by marisahoenig** [comment]
Test: manually run a migration and make sure app is running in db
