### ISSUE TITLE
FLUP: Create templates for direct deposit confirmations

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#366]
# Value Statement
**As** a veteran
**I want to** receive confirmation whenever I update direct deposit information
**So that** I have confidence the benefit will be deposited to the correct account

# Checklist
- [ ] Create direct deposit edu benefits email template under va.gov in dev/staging/prod: ~~[Content] (https://gist.github.com/lihanli/0531314d84be03dec669a891149ac060)~~ See content in comment from Todd below
- [ ] Create direct deposit comp & pen email template under va.gov in dev/staging/prod: ~~[Content](https://gist.github.com/lihanli/d5cf0e3bf021e512a341a9f4335aac7f)~~ See content in comment from Todd below

**Comment by ffafara-tw** [comment]
@miabecker @toddstanich Do we want to opine on the content?

**Comment by toddstanich** [comment]
Yes, assigned to myself to provide input on Monday.

**Comment by toddstanich** [comment]
Attaching a mockup. Waiting on response from team about what the personalization for benefit type should include. 

![direct-deposit](https://user-images.githubusercontent.com/56000470/107984318-4befa300-6f8d-11eb-8ec6-09aaf456cf67.jpg)

Your direct deposit information changed

We're sending this email to confirm that you've recently changed your direct deposit information in your VA.gov account profile. We'll use your updated information to deposit any [benefit type] benefits you may receive.

If you didn't make this change, please call us right away.

Call <a href="tel:1-800-827-1000">800-827-1000</a> (TTY: <a href="tel:1-800-829-4833">800-829-4833</a>). We're here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET. We can help you take the steps you need to protect your bank account information and prevent fraud.

<a href="https://www.va.gov/profile?utm_source=gov-delivery&utm_medium=email&utm_campaign=direct-deposit-edu-update">Go to your VA.gov profile</a>

—
You’re getting this email because you made a change to your information on VA.gov.

Please don’t reply to this email. If you need to contact us, go to https://www.va.gov.

**Comment by toddstanich** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19233

**Comment by saman-moshafi-va** [comment]
The template is created, but the header, "Your direct deposit information changed" breaks into two lines as the max width of the table is 600. Is this OK? Or this behavior should change?

**Comment by toddstanich** [comment]
@saman-moshafi-va This is okay. I don't think we should make any changes based on how headlines wrap based on this one headline.

**Comment by saman-moshafi-va** [comment]
* dev:
Education Template template id: a995dfe8-ee82-4f42-9ad4-ae82677683ab
Comp & Pen Template id: 779c9b42-9f53-4459-948e-54e51efc07a0
* staging:
Education Template template id: b0d2455b-cbbc-4b9b-9345-b468250d68e7
Comp & Pen Template id: 4f2752b7-179d-4b22-9445-47cceeced575
* prod:
Education Template template id: 879bfc33-3cb5-4c66-83b8-390c9dbe2af7
Comp & Pen Template id: 36d8ba76-9a08-4dfa-a044-7fe6ec267520

**Comment by miabecker** [comment]
Talk to them about adding checkboxes for email and text that way rich information can come. @miabecker

**Comment by miabecker** [comment]
@saman-moshafi-va cc @toddstanich commented on the ticket the va.gov team created on their side for this piece of work providing the details you gave above. Here is the link: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19233

Thanks Saman!

**Comment by saman-moshafi-va** [comment]
modified the Comp & Pen Template on dev, staging and prod to correct the va-profile URL
