### ISSUE TITLE
Run DB migrations before notification-api deployment

### ISSUE THREAD

**Issue by punitladtw** [department-of-veterans-affairs/notification-api#37]
As a notification developer, I want to do my database migrations before deploying the code.

Acceptance criteria:
**GIVEN** there is a code change
**WHEN** the deployment pipeline is running
**THEN** database migrations runs before the code is deployed.

**GIVEN** the pipeline is running
**WHEN** the database migration is successful
**THEN** the pipeline progresses to deploy the code.

**GIVEN** the pipeline is running
**WHEN** the database migration fails
**THEN** the pipeline does not deploy the code.

Checklist:
- [x] Add a step to the pipeline for database migrations.
- [x] Research how to get information if DB migration succeeded or failed, to then make the pipeline fail
- [x] Use something like `aws-ecs-render-task` to fill in image in task definition
- [x] Combine all the `aws ssm get-parameter` calls into one script

Some ideas to consider:
- ECS container dependency with COMPLETED status: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_dependson

Alternate approach to look at:
https://engineering.instawork.com/elegant-database-migrations-on-ecs-74f3487da99f

**Comment by ffafara-tw** [comment]
Interesting approach to consider:

**Comment by philherbert** [comment]
We've had some interesting experiences with Terraform when trying to use the [`postgresql` provider](https://www.terraform.io/docs/providers/postgresql/index.html), summed up by [this issue](https://github.com/terraform-providers/terraform-provider-postgresql/issues/2) - you can't create an AWS RDS instance resource, and then use the `postgresql` provider and point it that instance, because providers need to be initialised before resources.

If we do want to start doing Postgres stuff in Terraform, we could try [splitting the AWS and Postgres stuff into different apply steps](https://github.com/terraform-providers/terraform-provider-postgresql/issues/2#issuecomment-369341707), or alternatively, [this funky workaround](https://github.com/terraform-providers/terraform-provider-postgresql/issues/2#issuecomment-567887609) where Postgres seems to be configured to not immediately expect a successful connection.

**Comment by saman-moshafi-va** [comment]
@philherbert does task definition require portMappings (6011) to run migrations?
