### ISSUE TITLE
Create Toll Free Numbers - dev/staging

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#375]
Business Context: we want to move to using toll-free numbers due to AWS policy changes that go into effect in April.

Number to use for dev: +18337021549
Number to use for staging: +18555420534

Checklist:
- configure content for default keywords and start keyword for number in Pinpoint
  - [x] dev
  - [x] staging
- associate number to appropriate SNS topic
  - [x] dev
  - [x] staging
- [staging - update existing services to use toll-free number as default sms sender values
  - [x] Lighthouse
  - [x] va.gov
- update dev/staging default numbers in `config.py`
  - [x] dev
  - [x] staging
- [x] request separate toll free number for staging - [documentation](https://docs.aws.amazon.com/pinpoint/latest/userguide/settings-request-number.html)

Open Questions:
- Which SNS topic should we choose for dev/staging? **Answer: we are now using two separate numbers for dev and staging so just use the appropriate topic for the env**

Notes:
- Can't test with Skype number, need to use real phone number or Google Voice

**Comment by miabecker** [comment]
Filip created one for prod and one for staging.

**Comment by emilywu-tw** [comment]
@miabecker Ling and I modified this card and created a new one to integrate toll-free numbers into our systems. Originally we thought we could do it in #370 because it seemed like it would be a straightforward change based on what Ilya told us, but we encountered some issues described in the Business Context section of the description in this story. We decided to break it out of 370 so that we wouldn't have to block that card, which is technically done at this point.

**Comment by lingtran** [comment]
- create separate number

**Comment by lingtran** [comment]
Requested to unburn numbers from AWS support, case id: 8044344451

**Comment by lingtran** [comment]
We have made the following observations that we hypothesize are necessarily bugs, but rather features of Pinpoint system. @emilywu-tw and I will reach out to Ilya for clarification.

Observed that texts that begin with 'help' trigger the HELP default keyword response, which may just be how Pinpoint expects 'help' messages:
![Screen Shot 2021-03-01 at 11.03.29 AM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/1918593f-4c18-49df-8b9e-3a9ed59b3b2e)


Also observed that texts sent quickly in succession do not trigger any response, which could be due to transactional limits per second:
![Screen Shot 2021-03-01 at 11.03.42 AM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/d2668f7a-c122-4a66-a6db-f8cb50ce0e5f)
