### ISSUE TITLE
Create Toll Free Number - prod

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/notification-api#383]
Status update: Blocked by pinpoint-callback-lambda that needs to be deployed to prod in infra. When that is ready, we can deploy to prod.

+++++

Business Context: we want to move to using toll-free numbers due to AWS policy changes that go into effect in April. 

Number to use: +18334981539

Checklist:
- [x] configure content for default keywords and start keyword for number in Pinpoint
- [x] associate number to appropriate SNS topic
- [x] update existing services to use toll-free number as default sms sender values
  - [x] VANotify
  - [x] va.gov
  - [x] dmc
  - [x] vanotify-team
 - [x] Lighthouse
- [x] update prod default number in `config.py`

Notes:
- Can't test with Skype number, need to use real phone number or Google Voice

**Comment by lingtran** [comment]
We have made the following observations that we hypothesize are necessarily bugs, but rather features of Pinpoint system. @emilywu-tw and I will reach out to Ilya for clarification.

Observed that texts that begin with 'help' trigger the HELP default keyword response, which may just be how Pinpoint expects 'help' messages:
![Screen Shot 2021-03-01 at 11.03.29 AM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/1918593f-4c18-49df-8b9e-3a9ed59b3b2e)


Also observed that texts sent quickly in succession do not trigger any response, which could be due to transactional limits per second:
![Screen Shot 2021-03-01 at 11.03.42 AM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/d2668f7a-c122-4a66-a6db-f8cb50ce0e5f)
