### ISSUE TITLE
Upgrade Terraform and AWS provider version

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#418]
# Value Statement
**As** a VANotify developer
**I want to** upgrade Terraform and AWS provider version
**So that** I can make use of new features

# Additional Info/Resources
- https://www.terraform.io/upgrade-guides/0-15.html
- https://registry.terraform.io/providers/hashicorp/aws/2.59.0/docs/guides/version-3-upgrade
- Update tf version by version then run the complete pipeline (0.12 to 0.13, 0.13 to 0.14, etc)
- Check for syntax changes
- Need AWS access token for running locally (where to get?)
- Update AWS provider separately

**Comment by ffafara-tw** [comment]
In short: update Terraform, run terraform 0.13upgrade, run an apply without changing any of the structure (to "upgrade" the state), possibly fiddle with provider definitions for hours and hours, upgrade Terraform, run an apply without changing any of the structure, check-in the lockfile 0.14 creates

I think we had a problem running on our linux build server that we only included the hashes for the darwin binaries in the lockfile which failed the build. Make sure you include also the ones from all architectures you need...

make sure you make a backup of your state file in case something goes wrong. terraform 013upgrade might do one automatically.

You can use terraform state pull > state.json if you're using a remote state
But generally, I've never had Terraform "break" a state while upgrading

Think we saw this one: https://github.com/hashicorp/terraform/issues/27135

Do the Terraform upgrade first (!)
You do not want to mix state, provider and Terraform upgrades 😣

Beware of where you have projects that reference state from other projects. Upgrades and state changes may break. (Integrating by having a consumer directly access its provider's data structures is Bad, even though the tool vendor actively encourages it 😠)

We did that recently without experiencing any difficulty. The only little trap is the output format change (see below). While it's not really exhaustive, maybe our team checklist is useful. We also had a little shell script to generate a Jira table we could update to track progress. It uses .terraform-version, assuming we are using tfenv.

- When upgrading from v0.11.X, first upgrade to v0.12.30, then v0.13.6 and finally v0.14.5
- When upgrading from v0.12.X, first upgrade to v0.13.6 and finally v0.14.5
- When upgrading from v0.13.X to v0.14.5 we need to add the generated lock file to git, BUT before this we need to add lock information for ALL platforms (otherwise the repository becomes platform specific): terraform providers lock -platform=darwin_amd64 -platform=linux_amd64 -platform=windows_amd64
- When upgrading from vX to vY, we need to make a backup of the state (e.g. if it is stored in a AWS S3 bucket with versioning)
- When upgrading from vX to vY, we want to review terraform plan output even if we did not change infra code.
- When using terraform output, be sure to use the -raw flag or be aware of the relevant discussion (https://github.com/hashicorp/terraform/issues/26831)

To make it easy to track the progress across many repos, we can generate a table of terraform usage with the script below. It assumes (find_terraform_version, extract_terraform_version) we have a big directory where all the working copies of our repos are and we are visiting this directory (pwd) when running the script.
```
# terraform_version_report.sh
find_terraform_version()
{
    find . -type f -name .terraform-version
}

extract_terraform_version()
{
    while IFS='/' read _ repository path; do
	printf '%s|%s\n' "${repository}" $(cat "${repository}/${path}")
    done
}

sort_by_repository()
{
    sort -t'|' -k1 -u
}

format_jira_table()
{
    awk -F'|' '
function require_upgrade(version) {
  return (version < "0.13")
}

BEGIN {
    printf("||Repository||Terraform Version||Uses Terraform 0.13||\n")
}
   
{
  printf("|%s|%s|%s|\n", $1, $2, (require_upgrade($2) ? "(x)" : "(/)"))
}
'
}

find_terraform_version | extract_terraform_version | sort_by_repository | format_jira_table
```

**Comment by emilywu-tw** [comment]
<img width="1381" alt="Screen Shot 2021-05-04 at 3 46 43 PM" src="https://user-images.githubusercontent.com/34494609/117062263-433b7d00-acf1-11eb-8b78-a1abde55738f.png">
 proof that the versions have been updated in prod: https://github.com/department-of-veterans-affairs/vanotify-infra/runs/2494551616?check_suite_focus=true

**Comment by ffafara-tw** [comment]
@emilywu-tw any reason this story is in blocked/follow-up column?

**Comment by TWs-DevenS** [comment]
This is a infrastructure upgrade.
The upgrade is considered successful , 
1. given the developer has been able to access and / or evaluate the new features made available by the upgrade.
2. Attached is documentation of the upgrade procedure 
3 The implementation was Peer Reviewed.

Ticket can be closed
