### ISSUE TITLE
Add email costs

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#887]
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/platform_stats/rest.py#L97): Add email costs in [get_usage_for_all_services](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/platform_stats/rest.py#L81)
```
    # TODO: Add email costs?
    for s in sms_costs:
        entry = {
            "organisation_id": str(s.organisation_id) if s.organisation_id else "",
            "organisation_name": s.organisation_name or "",
            "service_id": str(s.service_id),
            "service_name": s.service_name,
            "sms_cost": float(s.sms_cost),
            "sms_fragments": s.chargeable_billable_sms,
            "letter_cost": 0,
            "letter_breakdown": ""
        }
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/887?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by jakehova** [comment]
Recommendation is to remove TODO because costs are not an input to determining which provider to use for sending email.  

If we were to do it, we would need to (at minimum): 
- [ ] Add Email Costs per Provider to db (FactBilling table)
- [ ] Add fetch email costs query to rest.py file 
- [ ] Add logic branch to  get_usage_for_all_services to determine if its an email provider to call the fetch costs

SES Email Pricing: https://aws.amazon.com/ses/pricing/

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/887?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
Closing as duplicate to #886
