### ISSUE TITLE
Github Actions - Node.js 12 is deprecated

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#909]
## Value Statement

**As** An Engineer
**I want to** to ensure Github Actions run smoothly
**So that** the CI/CD pipeline is not broken

We are using deprecated Actions:
```

Node.js 12 actions are deprecated. 
For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: 
aws-actions/configure-aws-credentials, aws-actions/configure-aws-credentials

```
Node.js 12 was no longer supported as of April 2022.

## Acceptance Criteria

**GIVEN** We push code or run an Action
**WHEN** The Action runs
**THEN** No deprecated warnings regarding Node.js

## Checklist

- [x] Deprecated warnings for `Node.js 12` are resolved

## Assumptions

- This is a configuration change

## Additional Info/Resources

- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/909?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718

**Comment by ldraney** [comment]
As a quick update, adding "-node16" to the relevant actions, as described in [this repo issue ](https://github.com/aws-actions/configure-aws-credentials/issues/489) associated with the error, gets rid of the errors, as they are somewhat superfluous and will be gone with the next major update, which will also apply to this new tag. 

The only delay now is I'm finding the best workflow for me to test, monitor, and upgrade our actions, while also working around a GUI bug we discovered with lambdas and workflow_calls.  Essentially, our devs currently need to run `gh workflow run -F choice=[myLambda] deploy_lambda_dev.yml -r  [branch]`.   or else the lambda deployed to dev is from master.  Since the GUI is currently our devs preference, this is my next objective before testing my changes.

**Comment by ldraney** [comment]
I've been playing with a new file that will help with the use and testing of future actions changes.  I'm writing an action to test the other actions, namely "testGithubActions.yml".  I'm working on various syntax issues, check my commit history.

**Comment by mjones-oddball** [comment]
@ldraney when you get a moment please move this to in progress in Zenhub since you're working on it :)

**Comment by ldraney** [comment]
***Things I learned
Called by dev_deploy.yml
Db-downgrade (kind of, it calls the task file but not this actual workflow).  Actually, db-downgrade is not being called at all!  
Deployment.yml (which is what actually overstepping db-downgrade, and instead directly calling the task file)
Lambda-functions
User_flows
twistlock
So the only workflows that need individual tests are: 
update-datadog-image.yaml
Load-test-email-delivery-time
Load-test-sms-response-time
Updated-cached-image
Update-datadog-image
For issue #909, I only need to individual test: 
update-datadog-image.yaml
Load-test-email-delivery-time
Load-test-sms-response-time

I successfully ran dev_deploy.yml with my associated changed to “-node16”.  
So my final task is to finish testGithubActions.yml for the three workflows mentioned above. 

**side note, userflows.yml isn’t working right, as noted in another issue.  I’ll be taking a look at that with my newfound knowledge!

**Comment by ldraney** [comment]
Even though the tests for Load-test-email-delivery-time.yml and Load-test-sms-response-time.yml failed, it is either because they are running in Dev, or because they aren't working to begin with.  Since that is outside the scope of this issue, and the relevant errors are gone, this ticket is ready to close.
