### ISSUE TITLE
Two-Way Lambda Code

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#923]
## Issue
Lambda must accept triggers from: 
- [x] SQS (feeder queue)

Lambda logic outline: 
1) Receive request
2) use "destinationNumber"(Amazon sender) to retrieve: request URL, service id, is self managed
3) make HTTP POST request with shared request body to request URL 
4) if fail then drop in replay queue

## Additional Information
- [Writeup](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Architecture/two_way_sms.md#lambda) on the plan for two-way sms

Example SNS Topic Message from Pinpoint:
```
{
  "originationNumber":"+14255550182",
  "destinationNumber":"+12125550101",
  "messageKeyword":"JOIN",
  "messageBody":"EXAMPLE",
  "inboundMessageId":"cae173d2-66b9-564c-8309-21f858e9fb84",
  "previousPublishedMessageId":"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
}
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/923?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718

**Comment by k-macmillan** [comment]
Initial work pushed in branch [923-two-way-sms-lambda](https://github.com/department-of-veterans-affairs/notification-api/tree/923-two-way-sms-lambda).
Still todo:
- SQS implemented
- Dead-letter implemented
- Testing

**Comment by k-macmillan** [comment]
This received a few updates. Github actions are in the branch. This has been handed over to @jakehova  because I do not have enough room on my plate for it.

**Comment by kalbfled** [comment]
I refactored the code and got all unit tests to pass.

**Comment by cris-oddball** [comment]
- v1.5.0 tag cut and released to Perf and Staging
- Melanie created an inbound number in staging using the API and associated it with the service for vetext using the create sms sender api route
- Additional configuration in AWS to set the correct queue on the number
- Tested lambda in staging directly for Happy Path using a copy/paste body taken from the actual logs and received a 200 with no errors

- Need to complete the remainder of testing.
- Issue 1011 opened to handle a url that is null not going to the retry queue
- Need to open tickets based on Jacob's comments above

**Comment by cris-oddball** [comment]
**QA IN PROGRESS ON STAGING**

**Happy Path** 
Sent a valid JSON object to the Test Event on the lambda, which results in a 200, the message being handed off to the `url_endpoint`.
Cloudwatch (truncated): 
```
[INFO]	2022-12-14T22:15:00.052Z	b20ff81c-b6a8-5a62-9448-a408fbb8e79e	Forwarding inbound SMS to service: a57c326a-2c37-4cdf-a2b7-a261bd5909b1. UrlEndpoint: https://eou9ebpdvxw3lva.m.pipedream.net/
[INFO]	2022-12-14T22:15:00.631Z	b20ff81c-b6a8-5a62-9448-a408fbb8e79e	POST to service complete
[INFO]	2022-12-14T22:15:00.632Z	b20ff81c-b6a8-5a62-9448-a408fbb8e79e	Response Status: 200
[DEBUG]	2022-12-14T22:15:00.632Z	b20ff81c-b6a8-5a62-9448-a408fbb8e79e	Response Content: b'<p><b>Success!</b></p>\n<p>To customize this response, check out our docs <a href="https://pipedream.com/docs/workflows/steps/triggers/#customizing-the-http-response">here</a></p>\n'
END RequestId: b20ff81c-b6a8-5a62-9448-a408fbb8e79e
```


**Negative - Invalid Event**
Select any event that is not an SQS event, results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Event" which is a JSON object that is not formatted as an SQS event:
```
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}
```
Cloudwatch (truncated): 
```
START RequestId: b2339280-4aaa-4252-ab7f-79e5ddce3cb4 Version: $LATEST
[CRITICAL]	2022-12-15T18:10:41.901Z	b2339280-4aaa-4252-ab7f-79e5ddce3cb4	Invalid event: {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
[WARNING]	2022-12-15T18:10:41.901Z	b2339280-4aaa-4252-ab7f-79e5ddce3cb4	Pushing event to DEAD LETTER queue
[DEBUG]	2022-12-15T18:10:41.901Z	b2339280-4aaa-4252-ab7f-79e5ddce3cb4	Event: {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
[INFO]	2022-12-15T18:10:42.062Z	b2339280-4aaa-4252-ab7f-79e5ddce3cb4	Completed enqueue of message
END RequestId: b2339280-4aaa-4252-ab7f-79e5ddce3cb4
```
In DLQ:
```
Message: d7ed89a7-ac22-420c-a950-df748a4f4f66
Body: {"key1": "value1", "key2": "value2", "key3": "value3"}
```



**Negative - Invalid Event Body**
Send an SQS event that does not have a proper `body` property, results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Body" - the body only should be sent to DLQ
Used Happy Path event with the body set to an empty string.
Cloudwatch (truncated): 
```
START RequestId: e95193d3-d46a-441f-b486-e20d65db1294 Version: $LATEST
[INFO]	2022-12-15T18:25:43.273Z	e95193d3-d46a-441f-b486-e20d65db1294	Processing an SQS inbound_sms record . . .
[WARNING]	2022-12-15T18:25:43.273Z	e95193d3-d46a-441f-b486-e20d65db1294	Pushing event to DEAD LETTER queue
[DEBUG]	2022-12-15T18:25:43.274Z	e95193d3-d46a-441f-b486-e20d65db1294	Event: 
[INFO]	2022-12-15T18:25:43.421Z	e95193d3-d46a-441f-b486-e20d65db1294	Completed enqueue of message
[ERROR]	2022-12-15T18:25:43.422Z	e95193d3-d46a-441f-b486-e20d65db1294	Malformed record body.
[ERROR]	2022-12-15T18:25:43.422Z	e95193d3-d46a-441f-b486-e20d65db1294	Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/task/two_way_sms_v2.py", line 159, in notify_incoming_sms_handler
    record_body = json.loads(record_body)
  File "/var/lang/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
END RequestId: e95193d3-d46a-441f-b486-e20d65db1294
```
In DLQ:
```
Message: 33857d90-e9b3-43a0-99ce-29399f36bee5
Body: ""
```


**Negative -  Phone Number not found in inbound_numbers table**
Send an SQS event that does not have a valid `destinationNumber` property `"destinationNumber\\\":\\\"+11111111111\\\",` results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Number" - the body only should be sent to DLQ
Used Happy Path with a bad number
Cloudwatch (truncated):
```
[INFO]	2022-12-15T18:33:55.883Z	f20dac38-7259-420a-b69f-d76a7f22f8d1	Processing an SQS inbound_sms record . . .
[WARNING]	2022-12-15T18:33:55.883Z	f20dac38-7259-420a-b69f-d76a7f22f8d1	Pushing event to DEAD LETTER queue
[INFO]	2022-12-15T18:33:56.033Z	f20dac38-7259-420a-b69f-d76a7f22f8d1	Completed enqueue of message
[CRITICAL]	2022-12-15T18:33:56.033Z	f20dac38-7259-420a-b69f-d76a7f22f8d1	Unable to find two_way_record for: +11111111111
END RequestId: f20dac38-7259-420a-b69f-d76a7f22f8d1
```
In DLQ:
Message: cb577c5b-10a4-40c9-9ce4-0a79f016f368
Body: was the full body with the incorrect destinationNumber - not posting here.


**Negative - Invalid URL**
Send an SQS event that does not have a valid `url_endpoint` property, results in a 200 and the message gets sent back to the feeder queue (retry) will retry for 4 days.
Need to update the URL on the actual inbound_number in API to test this. Setting it to http://foo.bar.
Cloudwatch (truncated):
```
START RequestId: f016ea97-ea28-4c45-82c1-83cd87536c3d Version: $LATEST
[INFO]	2022-12-15T18:46:17.695Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Processing an SQS inbound_sms record . . .
[INFO]	2022-12-15T18:46:17.695Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Forwarding inbound SMS to service: a57c326a-2c37-4cdf-a2b7-a261bd5909b1. UrlEndpoint: https://foo.bar
[ERROR]	2022-12-15T18:46:17.836Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	RequestException With Http Request
[ERROR]	2022-12-15T18:46:17.837Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	HTTPSConnectionPool(host='foo.bar', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc4b920ba60>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
Traceback (most recent call last): <snipped ALL the very long lines of this traceback>
[INFO]	2022-12-15T18:46:17.905Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Failed to make an HTTP request.  Placing the request back on retry.
[WARNING]	2022-12-15T18:46:17.905Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Pushing event to RETRY queue
[INFO]	2022-12-15T18:46:18.087Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Completed enqueue of message
[INFO]	2022-12-15T18:46:18.087Z	f016ea97-ea28-4c45-82c1-83cd87536c3d	Completed enqueue of message
```
Note: due to timing on this, very hard to actually see the messages being put back on the queue, trusting the log notes here.  There are additional logs that show that message was indeed put back on the queue and being retried.

Restoring the pipedream URL and purging the queue so that it doesn't needlessly keep trying,

**Comment by cris-oddball** [comment]
Lambda Test Event testing completed.

@mjones-oddball ready to start actually using the vetext endpoint. Also, I know that keywords and whatnot are supposed to be involved here - are we testing that? Like I send a text with a keyword and it does a thing?

**Comment by cris-oddball** [comment]
Update to above comment:

- we want to set the url to vetext > we need this URL
- we can leave staging at DEBUG
- we are not testing keywords.

**Comment by cris-oddball** [comment]
Updated URL on inbound number and received this
```
[ERROR]	2022-12-15T19:52:25.095Z	6ae6bf64-864c-4239-8819-98e893c01a50	HTTPError With Http Request
[ERROR]	2022-12-15T19:52:25.095Z	6ae6bf64-864c-4239-8819-98e893c01a50	401 Client Error: Unauthorized for url: https://staging.api.vetext.va.gov/api/vetext/pub/inbound-message/aws
```
Kyle to look into it.

**Comment by cris-oddball** [comment]
Jacob's notes above added to this [Google Doc](https://docs.google.com/document/d/1lr5L_c2xHMDqygFWuKOQl3J0b_E0m9YYehw0b_IdhFM/edit?usp=sharing)

**Comment by cris-oddball** [comment]
Result of the 401 error:

- Rob sent the username/password for their `/inbound-message/aws` endpoint. 
- This requires encoding the user/pass combo into base64 and sending it in as a header `'Authorization: Basic <encoded>'`
- I tested this out on CAG using Powershell to encode the user/pass, create a known good body, and send the POST request. I received a 200 response, so we know that this works.
- For now, the plan is to set it up to be able to send this auth header in the POST request in the lambda code and will revisit 'in the future'.
- Pausing testing until that work is merged then will send Dave's logging changes (already merged) and this new code to Perf and Staging and retest.

@mjones-oddball for visibility

**Comment by jakehova** [comment]
updated the code to include the vetext bearer token for the post.  Updated the unit tests to pass.  Also updated the infra to give the lambda access to the vetext token ssm param.

**Comment by cris-oddball** [comment]
**PASSED QA**

Hotfix deployed to Perf and Staging as v1.5.1. Resuming Testing with vetext endpoint.

**Happy Path**
Sent a valid JSON object to the Test Event on the lambda, which results in a 200, the message being handed off to the url_endpoint.
Cloudwatch :
```
[INFO]	2022-12-16T17:01:31.627Z		Getting the database URI from SSM Parameter Store . . .
[INFO]	2022-12-16T17:01:31.970Z		. . . Retrieved the database URI from SSM Parameter Store.
[INFO]	2022-12-16T17:01:32.058Z		. . . Retrieved the VeText AuthToken from SSM Parameter Store.
[INFO]	2022-12-16T17:01:32.058Z		Retrieving the 10DLC-to-URL mapping from the database . . .
[INFO]	2022-12-16T17:01:32.131Z		. . . Retrieved the 10DLC-to-URL mapping from the database.
START RequestId: eb35cc3f-d1e9-4455-a6af-f80b204a3900 Version: $LATEST
[INFO]	2022-12-16T17:01:32.143Z	eb35cc3f-d1e9-4455-a6af-f80b204a3900	POSTing the inbound SMS to service: a57c326a-2c37-4cdf-a2b7-a261bd5909b1. UrlEndpoint: https://staging.api.vetext.va.gov/api/vetext/pub/inbound-message/aws
/var/task/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'staging.api.vetext.va.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

**Negative - Invalid Event**
Select any event that is not an SQS event, results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Event" which is a JSON object that is not formatted as an SQS event.
Cloudwatch:
```
[INFO]	2022-12-16T17:07:50.124Z		Getting the database URI from SSM Parameter Store . . .
[INFO]	2022-12-16T17:07:50.466Z		. . . Retrieved the database URI from SSM Parameter Store.
[INFO]	2022-12-16T17:07:50.561Z		. . . Retrieved the VeText AuthToken from SSM Parameter Store.
[INFO]	2022-12-16T17:07:50.561Z		Retrieving the 10DLC-to-URL mapping from the database . . .
[INFO]	2022-12-16T17:07:50.636Z		. . . Retrieved the 10DLC-to-URL mapping from the database.
START RequestId: c0e011f8-d0e0-497b-ad76-9e36ccf40538 Version: $LATEST
[ERROR]	2022-12-16T17:07:50.647Z	c0e011f8-d0e0-497b-ad76-9e36ccf40538	Invalid event: {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
[WARNING]	2022-12-16T17:07:50.647Z	c0e011f8-d0e0-497b-ad76-9e36ccf40538	Pushing to the DEAD LETTER queue . . .
[WARNING]	2022-12-16T17:07:50.791Z	c0e011f8-d0e0-497b-ad76-9e36ccf40538	. . . Completed the SQS push.
END RequestId: c0e011f8-d0e0-497b-ad76-9e36ccf40538
```
In DLQ:
```
Message: 68e4c1ea-9b80-417f-842a-cc17b1416f25
Body: {"key1": "value1", "key2": "value2", "key3": "value3"}
```

**Negative - Invalid Event Body**
Send an SQS event that does not have a proper body property, results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Body" - the body only should be sent to DLQ
Used Happy Path event with the body set to an empty string.
Cloudwatch (truncated):
```
START RequestId: cf108375-d151-4eb1-8502-f6c6687ed70f Version: $LATEST
[ERROR]	2022-12-16T17:12:42.153Z	cf108375-d151-4eb1-8502-f6c6687ed70f <snipped traceback>
[ERROR]	2022-12-16T17:12:42.154Z	cf108375-d151-4eb1-8502-f6c6687ed70f	Malformed record body: 
[WARNING]	2022-12-16T17:12:42.154Z	cf108375-d151-4eb1-8502-f6c6687ed70f	Pushing to the DEAD LETTER queue . . .
[WARNING]	2022-12-16T17:12:42.326Z	cf108375-d151-4eb1-8502-f6c6687ed70f	. . . Completed the SQS push.
END RequestId: cf108375-d151-4eb1-8502-f6c6687ed70f
```
In DLQ:
```
Message: 5731f05d-4268-4c3f-9599-3cca230c5c7d
Body: ""
```

**Negative - Phone Number not found in inbound_numbers table**
Send an SQS event that does not have a valid destinationNumber property "destinationNumber\\\":\\\"+11111111111\\\", results in a 200 and the message dropped in the DLQ - using Test Event "Negative-Invalid-Number" - the body only should be sent to DLQ
Used Happy Path with a bad number
Cloudwatch (truncated):
```
START RequestId: 343f7843-841a-4ed4-8b55-42aa865f0254 Version: $LATEST
[ERROR]	2022-12-16T17:16:20.872Z	343f7843-841a-4ed4-8b55-42aa865f0254	Unable to find a two_way_record for +11111111111.
[WARNING]	2022-12-16T17:16:20.872Z	343f7843-841a-4ed4-8b55-42aa865f0254	Pushing to the DEAD LETTER queue . . .
[WARNING]	2022-12-16T17:16:21.025Z	343f7843-841a-4ed4-8b55-42aa865f0254	. . . Completed the SQS push.
END RequestId: 343f7843-841a-4ed4-8b55-42aa865f0254
REPORT RequestId: 343f7843-841a-4ed4-8b55-42aa865f0254	Duration: 157.11 ms	Billed Duration: 158 ms	Memory Size: 128 MB	Max Memory Used: 84 MB	
```
DLQ:
```
Message: ba22f9f9-5997-4761-ad8d-6c7c991eb65e
Body included the incorrect phone, not posting due to length of message.
```

**Negative - Invalid URL**
Not testing this. We are releasing with vetext's URL, which requires an auth header, will handle this negative test event once we deal with authentication for other services.


Removing QA label but leaving in this lane until vetext has a chance to test this. 

@mjones-oddball ready for vetext testing.

@k-macmillan Note that the DLQ was set to "Maximum message count: 10" which prevented me from seeing all things in the DLQ. On staging I bumped this up to 25 so that I could see all the messages in the queue. Just something to note. Also, LOG_LEVEL	was set back to INFO on the deploy. Changed it to DEBUG. Is there a way to automate this setting to leave it on DEBUG for the lower environments?
